const X11Colors = [
   // X11 color space,
   // see http://www.xfree86.org/current/X.7.html#toc10 
   // see /usr/share/X11/rgb.txt
   // see http://en.wikipedia.org/wiki/X11_color_names
   //
   // Suggested color use in comments is according to
   // http://wiki.openstreetmap.org/wiki/User:Skippern/INT-1
   //

   {val: "#000000", name: "black"},              // Border: Gray, Buildings, General Symbols, Text: Black 
   {val: "#000080", name: "navy"},
   {val: "#00008B", name: "darkblue"},
   {val: "#0000CD", name: "mediumblue"},
   {val: "#0000FF", name: "blue"},
   {val: "#006400", name: "darkgreen"},
   {val: "#008000", name: "green"},
   {val: "#008080", name: "teal"},
   {val: "#008B8B", name: "darkcyan"},           // Special 
   {val: "#00BFFF", name: "deepskyblue"},
   {val: "#00CED1", name: "darkturquoise"},
   {val: "#00FA9A", name: "mediumspringgreen"},
   {val: "#00FF00", name: "lime"},               // Light: Green 
   {val: "#00FF7F", name: "springgreen"},
   {val: "#00FFFF", name: "aqua"},
   {val: "#00FFFF", name: "cyan"},
   {val: "#191970", name: "midnightblue"},
   {val: "#1E90FF", name: "dodgerblue"},
   {val: "#20B2AA", name: "lightseagreen"},
   {val: "#228B22", name: "forestgreen"},        // Border: Green, Text: Green 
   {val: "#2E8B57", name: "seagreen"},
   {val: "#2F4F4F", name: "darkslategray"},
   {val: "#32CD32", name: "limegreen"},
   {val: "#3CB371", name: "mediumseagreen"},
   {val: "#40E0D0", name: "turquoise"},
   {val: "#4169E1", name: "royalblue"},
   {val: "#4682B4", name: "steelblue"},
   {val: "#483D8B", name: "darkslateblue"},
   {val: "#48D1CC", name: "mediumturquoise"},
   {val: "#4B0082", name: "indigo"},
   {val: "#556B2F", name: "darkolivegreen"},
   {val: "#5F9EA0", name: "cadetblue"},
   {val: "#6495ED", name: "cornflowerblue"},
   {val: "#66CDAA", name: "mediumaquamarine"},
   {val: "#696969", name: "dimgray"},
   {val: "#6A5ACD", name: "slateblue"},
   {val: "#6B8E23", name: "olivedrab"},
   {val: "#708090", name: "slategray"},
   {val: "#778899", name: "lightslategray"},
   {val: "#7B68EE", name: "mediumslateblue"},
   {val: "#7CFC00", name: "lawngreen"},
   {val: "#7FFF00", name: "chartreuse"},
   {val: "#7FFFD4", name: "aquamarine"},
   {val: "#800000", name: "maroon"},
   {val: "#800080", name: "purple"},
   {val: "#808000", name: "olive"},
   {val: "#808080", name: "gray"},
   {val: "#87CEEB", name: "skyblue"},            // Shallow Water 
   {val: "#87CEFA", name: "lightskyblue"},
   {val: "#8A2BE2", name: "blueviolet"},
   {val: "#8B0000", name: "darkred"},
   {val: "#8B008B", name: "darkmagenta"},        // Amenities, Border: Magenta, Light: Magenta, Services, Text: Magenta 
   {val: "#8B4513", name: "saddlebrown"},
   {val: "#8FBC8F", name: "darkseagreen"},       // Border: Green (shading), Tidal Zone 
   {val: "#90EE90", name: "lightgreen"},
   {val: "#9370DB", name: "mediumpurple"},
   {val: "#9400D3", name: "darkviolet"},
   {val: "#98FB98", name: "palegreen"},
   {val: "#9932CC", name: "darkorchid"},
   {val: "#9ACD32", name: "yellowgreen"},
   {val: "#A0522D", name: "sienna"},
   {val: "#A52A2A", name: "brown"},
   {val: "#A9A9A9", name: "darkgray"},
   {val: "#ADD8E6", name: "lightblue"},          // Deep Water 
   {val: "#ADFF2F", name: "greenyellow"},
   {val: "#AFEEEE", name: "paleturquoise"},
   {val: "#B0C4DE", name: "lightsteelblue"},
   {val: "#B0E0E6", name: "powderblue"},
   {val: "#B22222", name: "firebrick"},
   {val: "#B8860B", name: "darkgoldenrod"},      // Buildings, Urban Areas 
   {val: "#BA55D3", name: "mediumorchid"},
   {val: "#BC8F8F", name: "rosybrown"},
   {val: "#BDB76B", name: "darkkhaki"},
   {val: "#C0C0C0", name: "silver"},
   {val: "#C71585", name: "mediumvioletred"},
   {val: "#CD5C5C", name: "indianred"},
   {val: "#CD853F", name: "peru"},
   {val: "#D2691E", name: "chocolate"},
   {val: "#D2B48C", name: "tan"},
   {val: "#D3D3D3", name: "lightgray"},          // Border: Gray (shading) 
   {val: "#D8BFD8", name: "thistle"},            // Border: Magenta (shading) 
   {val: "#DA70D6", name: "orchid"},
   {val: "#DAA520", name: "goldenrod"},
   {val: "#DB7093", name: "palevioletred"},
   {val: "#DC143C", name: "crimson"},
   {val: "#DCDCDC", name: "gainsboro"},
   {val: "#DDA0DD", name: "plum"},
   {val: "#DEB887", name: "burlywood"},
   {val: "#E0FFFF", name: "lightcyan"},
   {val: "#E6E6FA", name: "lavender"},
   {val: "#E9967A", name: "darksalmon"},
   {val: "#EE82EE", name: "violet"},
   {val: "#EEE8AA", name: "palegoldenrod"},
   {val: "#F08080", name: "lightcoral"},
   {val: "#F0E68C", name: "khaki"},
   {val: "#F0F8FF", name: "aliceblue"},          // Medium Water 
   {val: "#F0FFF0", name: "honeydew"},
   {val: "#F0FFFF", name: "azure"},
   {val: "#F4A460", name: "sandybrown"},
   {val: "#F5DEB3", name: "wheat"},
   {val: "#F5F5DC", name: "beige"},
   {val: "#F5F5F5", name: "whitesmoke"},
   {val: "#F5FFFA", name: "mintcream"},
   {val: "#F8F8FF", name: "ghostwhite"},
   {val: "#FA8072", name: "salmon"},
   {val: "#FAEBD7", name: "antiquewhite"},
   {val: "#FAF0E6", name: "linen"},
   {val: "#FAFAD2", name: "lightgoldenrodyellow"},
   {val: "#FDF5E6", name: "oldlace"},
   {val: "#FF0000", name: "red"},                // Light: Red, Text: Red 
   {val: "#FF00FF", name: "fuchsia"},
   {val: "#FF00FF", name: "magenta"},
   {val: "#FF1493", name: "deeppink"},
   {val: "#FF4500", name: "orangered"},
   {val: "#FF6347", name: "tomato"},
   {val: "#FF69B4", name: "hotpink"},
   {val: "#FF7F50", name: "coral"},
   {val: "#FF8C00", name: "darkorange"},
   {val: "#FFA07A", name: "lightsalmon"},
   {val: "#FFA500", name: "orange"},
   {val: "#FFB6C1", name: "lightpink"},
   {val: "#FFC0CB", name: "pink"},
   {val: "#FFD700", name: "gold"},
   {val: "#FFDAB9", name: "peachpuff"},
   {val: "#FFDEAD", name: "navajowhite"},        // Land 
   {val: "#FFE4B5", name: "moccasin"},
   {val: "#FFE4C4", name: "bisque"},
   {val: "#FFE4E1", name: "mistyrose"},
   {val: "#FFEBCD", name: "blanchedalmond"},
   {val: "#FFEFD5", name: "papayawhip"},
   {val: "#FFF0F5", name: "lavenderblush"},
   {val: "#FFF5EE", name: "seashell"},
   {val: "#FFF8DC", name: "cornsilk"},
   {val: "#FFFACD", name: "lemonchiffon"},
   {val: "#FFFAF0", name: "floralwhite"},
   {val: "#FFFAFA", name: "snow"},
   {val: "#FFFF00", name: "yellow"},             // Artificial Islands, Light: Yellow 
   {val: "#FFFFE0", name: "lightyellow"},
   {val: "#FFFFF0", name: "ivory"},
   {val: "#FFFFFF", name: "white"},              // Deeper Water 
];

